### ISSUE TITLE
Does the server support asp.net core 2.2

### ISSUE THREAD

**Issue by charleszhn** [kklldog/AgileConfig#1]
hello ,Thank you for developing this framework，I want to deploy this software on Windows server 2008 r2, but 08R2 only supports net core 2.2. A lot of net core 3.1 is referenced in the software. Can you provide a version that supports net core 2.2 ?

**Comment by kklldog** [comment]
Actualy，i developed this project by core 2.2 before this commit https://github.com/kklldog/AgileConfig/commit/a16a3516f428cb28d287a457ace3c435b2adde84 .
You can checkout any version that before this commit , then merge the latest code manual 。
I really suggest you that use docker to deply this poject .
My english is not good , i wish can help you .

**Comment by kklldog** [comment]
> hello ,Thank you for developing this framework，I want to deploy this software on Windows server 2008 r2, but 08R2 only supports net core 2.2. A lot of net core 3.1 is referenced in the software. Can you provide a version that supports net core 2.2 ?

Actualy，i developed this project by core 2.2 before this commit a16a351 .
You can checkout any version that before this commit , then merge the latest code manual 。
I really suggest you that use docker to deply this poject .
My english is not good , i wish can help you .

**Comment by charleszhn** [comment]
ok，Currently in trial...
