### ISSUE TITLE
不考虑下 增加 LiteDB支持？

### ISSUE THREAD

**Issue by sgf** [kklldog/AgileConfig#12]
LiteDB--原生C# nosql数据库
LiteDB 就在  github

**Comment by kklldog** [comment]
看了下介绍好像跟Sqlite比较类似，本地文件数据库跟服务端程序放一起的话生产风险比较大。如果是开发测试环境的话sqlite也可以了，感觉没啥必要啊。

**Comment by sgf** [comment]
> 看了下介绍好像跟Sqlite比较类似，本地文件数据库跟服务端程序放一起的话生产风险比较大。如果是开发测试环境的话sqlite也可以了，感觉没啥必要啊。

重点是原生C#

**Comment by kklldog** [comment]
> > 看了下介绍好像跟Sqlite比较类似，本地文件数据库跟服务端程序放一起的话生产风险比较大。如果是开发测试环境的话sqlite也可以了，感觉没啥必要啊。
> 
> 重点是原生C#(不用携带任何native dll) ，而且是nosql（不用写sql语句，当然也支持sql）。
> 另外，其实我的意图其实是没有Master，并且把LiteDB这种本地数据库作为每一个NodeServer的配置存储方式，在线的NodeServer，谁的版本最新，就推到其他的Node，然后任何NodeServer下线后都是通过本地数据库保存当前状态的配置，启动后拉取任意在线节点最新的配置版本直到追上全网最新配置的版本（当然我不是特别清楚分布式的实现。）。
> 看你的架构图，你现在DB是中心化的么，DB是似乎是中心？

明白你的意思了。你是要去中心DB。你说的没错现在的架构DB就是中心化的，但是本身DB就是有它自己的高可用的技术，比如Sqlserver的always on技术，Mysql的binlog等。比如其他业务系统也是如此，尽管做分布式的或者多实例部署但大部分DB特别是关系型DB都是依靠DB自己相关的技术来实现高可用的。其实携程的apollo你看架构，也是有中心configdb的。
当然了去DB分布式存储也是可以搞的，比如什么raft协议拉，闲的慌的或许我会试试：）

**Comment by sgf** [comment]
> > > 看了下介绍好像跟Sqlite比较类似，本地文件数据库跟服务端程序放一起的话生产风险比较大。如果是开发测试环境的话sqlite也可以了，感觉没啥必要啊。
> > 
> > 
> > 重点是原生C#(不用携带任何native dll) ，而且是nosql（不用写sql语句，当然也支持sql）。
> > 另外，其实我的意图其实是没有Master，并且把LiteDB这种本地数据库作为每一个NodeServer的配置存储方式，在线的NodeServer，谁的版本最新，就推到其他的Node，然后任何NodeServer下线后都是通过本地数据库保存当前状态的配置，启动后拉取任意在线节点最新的配置版本直到追上全网最新配置的版本（当然我不是特别清楚分布式的实现。）。
> > 看你的架构图，你现在DB是中心化的么，DB是似乎是中心？
> 
> 明白你的意思了。你是要去中心DB。你说的没错现在的架构DB就是中心化的，但是本身DB就是有它自己的高可用的技术，比如Sqlserver的always on技术，Mysql的binlog等。比如其他业务系统也是如此，尽管做分布式的或者多实例部署但大部分DB特别是关系型DB都是依靠DB自己相关的技术来实现高可用的。其实携程的apollo你看架构，也是有中心configdb的。
> 当然了去DB分布式存储也是可以搞的，比如什么raft协议拉，闲的慌的或许我会试试：）

好 我只是提一提，哈哈，我本身并不是特别懂分布式之类的。
