### ISSUE TITLE
关于发布的问题

### ISSUE THREAD

**Issue by weiwoducui** [kklldog/AgileConfig#14]
我自己下载了源代码后，修改完appsetting的数据库配置后，使用AgileConfig.Server.Apisite能启动项目，但是想发布到本地使用发现发布的程序无法启动。请问这个项目想本地发布该怎么操作

**Comment by kklldog** [comment]
正常按.net core的项目发布即可，如果用iis host，可能需要安装asp.net core host bundle 这个runtime，里面包含了ASP.NET Core Module v2 这个模块，不然跑不起来。
