### ISSUE TITLE
项目很好,但却无法保证一致性.建议加入zookeeper.

### ISSUE THREAD

**Issue by xiaolu6t** [kklldog/AgileConfig#15]
不能保证配置的一致性,我想大多数人还是考虑使用Docker的Apollo配置中心.

**Comment by kklldog** [comment]
> 不能保证配置的一致性,我想大多数人还是考虑使用Docker的Apollo配置中心.

为啥不能保证一致性啊，我其实存的存的是数据库啊，所有节点其实是读的同一个数据库，笑哭
