### ISSUE TITLE
镜像文件过大（1.59GB），建议采用如下方式构建以缩减镜像大小，修改后为281MB

### ISSUE THREAD

**Issue by botao-xu** [kklldog/AgileConfig#16]
**修改方式：**
1. 修改Dockerfile内容如下，并将Dockerfile移动到AgileConfig.Server.Apisite项目下，并修改该文件的属性“Copy to output Directory”为“Copy always”.
    _**FROM mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim AS base
    WORKDIR /app
    EXPOSE 5000
    COPY . /app
    ENTRYPOINT ["dotnet", "AgileConfig.Server.Apisite.dll"]**_
2. 发布项目AgileConfig.Server.Apisite，发布目录如“\AgileConfigmaster\AgileConfig.Server.Apisite\bin\Release\netcoreapp3.1\publish”
3. 切换到发布目录，执行构建命令"**_docker build -t agile_config ._**"

**修改前镜像大小：**
![image](https://user-images.githubusercontent.com/8169639/100694026-20670e80-33c9-11eb-89f6-8289c1c7d9e0.png)
**修改后镜像大小：**
![image](https://user-images.githubusercontent.com/8169639/100695426-24e0f680-33cc-11eb-8bb8-fc39dc898364.png)

**Comment by botao-xu** [comment]
原方式镜像过大的主要原因是dotnet restore会先下载项目所需要的依赖包到本地目录，而这部分依赖包在项目发布后已经存在于publish目录了，所以相当于在镜像中这些依赖包占用了双倍空间。
修改后的方式直接在发布后的目录中构建镜像，不存在上述问题。

**Comment by azrng** [comment]
确实   这个包确实有一点大了，本地拉取得好久

**Comment by kklldog** [comment]
> 我认为原方式镜像过大有以下两点原因：
> 
> 1. 基于dotnet/core/sdk:3.1-buster而不是dotnet/core/aspnet:3.1-buster-slim构建镜像，本项目是aspnet项目，如果没有特殊需
>    要，可以使用镜像更小的 aspnet:3.1-buster-slim。
> 2. 镜像既包含了编译过程中由于使用了各种依赖产生的空间，也包含了编译结束后的发布目录产生的空间，但是编译过程中
>    的空间与运行时无关，不需要包含在镜像文件中。修改后的方式直接在发布后的目录中构建镜像，不存在上述问题。

感谢指出！
1.不使用sdk的镜像没办法在容器内部编译发布，这样我就不能用dockerhub的autobuild直接打包了。我就要本地编译然后打包了，然后手动push到dockerhub上去，不知道您啊有什么好办法。
2.为什么我使用了bionic这个tag，因为我另外一个项目使用3.1的某个镜像SqlServer的provider有bug，测试下来bionic这个镜像没有问题，所以我这里直接选用了bionic这个镜像。

**Comment by kklldog** [comment]
> 确实 这个包确实有一点大了，本地拉取得好久

哈哈，我想办法改进下。

**Comment by botao-xu** [comment]
> > 我认为原方式镜像过大有以下两点原因：
> > 
> > 1. 基于dotnet/core/sdk:3.1-buster而不是dotnet/core/aspnet:3.1-buster-slim构建镜像，本项目是aspnet项目，如果没有特殊需
> >    要，可以使用镜像更小的 aspnet:3.1-buster-slim。
> > 2. 镜像既包含了编译过程中由于使用了各种依赖产生的空间，也包含了编译结束后的发布目录产生的空间，但是编译过程中
> >    的空间与运行时无关，不需要包含在镜像文件中。修改后的方式直接在发布后的目录中构建镜像，不存在上述问题。
> 
> 感谢指出！
> 1.不使用sdk的镜像没办法在容器内部编译发布，这样我就不能用dockerhub的autobuild直接打包了。我就要本地编译然后打包了，然后手动push到dockerhub上去，不知道您啊有什么好办法。
> 2.为什么我使用了bionic这个tag，因为我另外一个项目使用3.1的某个镜像SqlServer的provider有bug，测试下来bionic这个镜像没有问题，所以我这里直接选用了bionic这个镜像。

可以在Visual Studio 2019中安装Docker支持，之后右键项目可以按照如下方式添加标准的Dockerfile文件模板
![image](https://user-images.githubusercontent.com/8169639/100709170-94fd7580-33e8-11eb-9a85-a9356a8ae1bb.png)
 @按照这种方式可以有效减少镜像的大小，我本地构建后是263MB，原理就是通过分阶段构建并且分离编译和运行，最后把publish的结果复制到一个单独的镜像文件中。我提交了PR https://github.com/kklldog/AgileConfig/pull/18，你可以试一下。
具体解释可以参考下面的文章：
译文：https://blog.csdn.net/cunfusq0176/article/details/109051411
原文：https://www.hanselman.com/blog/optimizing-aspnet-core-docker-image-sizes

**Comment by kklldog** [comment]
这个牛逼 晚上我测试下，没问题合并进去

**Comment by kklldog** [comment]
已经合并进去了，太牛逼了。
