### ISSUE TITLE
应用Id长度不能超过8位

### ISSUE THREAD

**Issue by WHJmaxne** [kklldog/AgileConfig#2]
我在创建应用的时候并没有提示，在创建配置的时候提示“应用Id长度不能超过8位;”

![image](https://user-images.githubusercontent.com/24425190/86071158-2589ff80-bab1-11ea-95d0-531a62dc4c1d.png)

**Comment by kklldog** [comment]
> 我在创建应用的时候并没有提示，在创建配置的时候提示“应用Id长度不能超过8位;”
> 
> ![image](https://user-images.githubusercontent.com/24425190/86071158-2589ff80-bab1-11ea-95d0-531a62dc4c1d.png)

已修复bug，使用最新的镜像试试。

**Comment by kklldog** [comment]
如果确认修复的话，告知一下

**Comment by WHJmaxne** [comment]
> 如果确认修复的话，告知一下

没问题了
