### ISSUE TITLE
希望能通过API维护配置内容

### ISSUE THREAD

**Issue by wzxinchen** [kklldog/AgileConfig#20]
我在基于amis写低代码平台，想用这个配置中心，希望能实现在我的平台中能直接操作配置中心

**Comment by kklldog** [comment]
最近太忙了，要不大佬您亲自动手得了，哈哈

**Comment by kklldog** [comment]
dalao
https://github.com/kklldog/AgileConfig/wiki/Restful-API

**Comment by wzxinchen** [comment]
可以可以
