### ISSUE TITLE
继承应用后相应配置的keyvalue没有继承过去

### ISSUE THREAD

**Issue by endysaiwang** [kklldog/AgileConfig#21]
相似项目应用配置大致一样（共同的配置内容）
虽然，在新建应用时，可以选择继承应用，但发现相应配置并没有继承
![image](https://user-images.githubusercontent.com/4568933/108580338-13bddb00-7366-11eb-9083-1aa47c265e38.png)

，建议再提供导出现有应用json配置功能，让配置人员到另外一个应用中可以导入该配置；

**Comment by kklldog** [comment]
你用客户端连接上是可以获取到继承的配置的，这是这个列表里没有显示而已。或许我可以加个开关，显示继承配置。

**Comment by endysaiwang** [comment]
不，我的意思是相近的配置，例如我A应用，数据库连接、日志、Redis等，另外一个应用B，同样需要这些配置，但不是完全一样，这时我觉得需要一个简易化的迁移操作，并且需要在界面上编辑修改

**Comment by endysaiwang** [comment]
导出json还有利于把线上的配置，还原到本地环境（local 环境一般采用appsetting.json？）

**Comment by kklldog** [comment]
> 不，我的意思是相近的配置，例如我A应用，数据库连接、日志、Redis等，另外一个应用B，同样需要这些配置，但不是完全一样，这时我觉得需要一个简易化的迁移操作，并且需要在界面上编辑修改

有点明白了，后面考虑加入

**Comment by bao2314483** [comment]
1.我觉得配置不应该以kv形式存储,我觉得应该像nacso那样,key对文档格式(json,yml,txt)这样存储,不但满足kv还可以满足多层次的配置需求,
2.对配置加密功能,因为winfrom端对于这个需求非常重要
3.我看你源码有用到socket,连接是存在一个静态变量上,对于多节点部署,你socket没有用redis作为底板,不知道你是怎么对socket负载均衡
其实还有几点建议的,不过还是算了,怕说多你不高心,哈哈

**Comment by kklldog** [comment]
> 1.我觉得配置不应该以kv形式存储,我觉得应该像nacso那样,key对文档格式(json,yml,txt)这样存储,不但满足kv还可以满足多层次的配置需求,
> 2.对配置加密功能,因为winfrom端对于这个需求非常重要
> 3.我看你源码有用到socket,连接是存在一个静态变量上,对于多节点部署,你socket没有用redis作为底板,不知道你是怎么对socket负载均衡
> 其实还有几点建议的,不过还是算了,怕说多你不高心,哈哈

1. json yml txt 不多是string么，你value存json，yml，txt 这取决于你啊。1.1.9之前的ui是支持json yml格式化的。
2. 为啥winform端加密重要，winfrom端也是要server端的吧？另外你value你可以自己加密啊。就算agileconfig server来加，agileconfig client来解密，那么别有用心的人拿着client来解密就行了啊，况且代码全是开源的。
3. 多节点部署，每个节点上都会有一个list来维护websocket client。client随机连接至任意一个节点，这就是负载均衡了。这个跟redis有啥关系啊。。。
4. 大家讨论，没啥不高兴的 ：）

**Comment by kklldog** [comment]
已支持导出json release-1.2.3

**Comment by kklldog** [comment]
> > 
> 
> 针对第三点，我猜测@bao2314483 的意思是说多节点时，如果客户端只随机连接到其中一个节点，当另一个节点收到变更时，所通知到的客户端不包含这些，所以需要利用一种机制通知到其他websocket server节点（比如redis的发布订阅模式），然后再通知到受影响的客户端。我没有仔细查阅 AgileConfig 的代码，所以我不确定这个是否是一个问题。

不会的，节点是受控制台管理的，当控制台发布一个新配置的时候，所有的节点都会收到消息，然后节点再找出需要更新的client通知他们更新配置。

**Comment by kklldog** [comment]
> 1.我觉得配置不应该以kv形式存储,我觉得应该像nacso那样,key对文档格式(json,yml,txt)这样存储,不但满足kv还可以满足多层次的配置需求, 2.对配置加密功能,因为winfrom端对于这个需求非常重要 3.我看你源码有用到socket,连接是存在一个静态变量上,对于多节点部署,你socket没有用redis作为底板,不知道你是怎么对socket负载均衡 其实还有几点建议的,不过还是算了,怕说多你不高心,哈哈

现在配置已经支持josn，text的编辑模式，但是存储在数据库里还是kv 。

**Comment by 944332213** [comment]
> > > 
> > 
> > 
> > 针对第三点，我猜测@bao2314483 的意思是说多节点时，如果客户端只随机连接到其中一个节点，当另一个节点收到变更时，所通知到的客户端不包含这些，所以需要利用一种机制通知到其他websocket server节点（比如redis的发布订阅模式），然后再通知到受影响的客户端。我没有仔细查阅 AgileConfig 的代码，所以我不确定这个是否是一个问题。
> 
> 不会的，节点是受控制台管理的，当控制台发布一个新配置的时候，所有的节点都会收到消息，然后节点再找出需要更新的client通知他们更新配置。

控制台连接到了所有节点，巧妙的思路。谢谢你的时间和解答。
另外，为了更好的宣传，参照 Apollo 我建议可以维护一个正在使用的企业列表，这可以帮助其他人选择，我甚至看到了有人在询问是否在生产环境使用。
而且也许可以编写其他语言的SDK（比如Java，他们实在太多了，在中国）
我之前本来有个SignalR+Blazor的思路，看到了作者这个，谢谢作者的作品😊😘

**Comment by kklldog** [comment]
> 

恩恩 好建议，主要是没空啊，
java，go 的 client sdk 我是有想写的。

**Comment by kklldog** [comment]
对了 你star了没，差2个800，看这蛋疼，哈哈

**Comment by 944332213** [comment]
> 

免费星星之前就给了😆
