### ISSUE TITLE
建议环境变量参数不要用冒号等特殊字符

### ISSUE THREAD

**Issue by xwb2535** [kklldog/AgileConfig#22]
在一些K8S管理工具下，特殊字符不被支持
Validation failed in API: Deployment.apps "agile-config" is invalid: [spec.template.spec.containers[0].env[2].name: Invalid value: "db:conn": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'), spec.template.spec.containers[0].env[3].name: Invalid value: "db:provider": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')]

**Comment by kklldog** [comment]
使用2个短横 __ 代替 ： 试试。
