### ISSUE TITLE
控制台页面404

### ISSUE THREAD

**Issue by gywei** [kklldog/AgileConfig#23]
下载源码。还原nuget,配置数据库正常，设置AgileConfig.Server.Apisite 为启动项，调试发现跳转

http://localhost:5000/ui#/user/initpassword
页面出不来。

配置如下：

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "System": "Warning",
      "Microsoft": "Warning"
    }
  },
  "adminConsole": true,
  "preview_mode": false,
  "db": {
    "provider": "sqlserver", //sqlite,mysql,sqlserver,npgsql,oracle
    //"conn": ""
    "conn": "Data Source=xxxxx;User ID=sa;Password=11223Initial Catalog=ApolloConfig;Pooling=true;Min Pool Size=1"
    //"conn": "Persist Security Info = False; User ID =dev; Password =dev@123; Initial Catalog =agile_config; Server =."
  },
  "JwtSetting": {
    "SecurityKey": "dfasf343453fsdfa,./,./sdfasf34r3hfhfdb", // 密钥
    "Issuer": "agileconfig.admin", // 颁发者
    "Audience": "agileconfig.admin", // 接收者
    "ExpireSeconds": 86400 // 过期时间
  }
}

**Comment by kklldog** [comment]
因为现在是个前后的分离项目，所以直接运行服务端源码，需要手工编译react-ui项目 npm install npm run build，然后复制dist文件到wwwwroot/ui目录。
