### ISSUE TITLE
请问修改配置会动态修改appconfig配置文件吗

### ISSUE THREAD

**Issue by ysq5202121** [kklldog/AgileConfig#24]
所有节点都挂了，是不是从appconfig里面读取配置，还是有专门的缓存文件,
直接修改appconfig这样不是更加好吗

**Comment by kklldog** [comment]
> 所有节点都挂了，是不是从appconfig里面读取配置，还是有专门的缓存文件,
> 直接修改appconfig这样不是更加好吗

每次拉取配置成功会在本地存一个备份，如果所有节点都连不上会从这个备份读取，不会从本地的appsettings.json读取。这个备份会比你的appsettingjson新。

**Comment by ysq5202121** [comment]
> > 所有节点都挂了，是不是从appconfig里面读取配置，还是有专门的缓存文件,
> > 直接修改appconfig这样不是更加好吗
> 
> 每次拉取配置成功会在本地存一个备份，如果所有节点都连不上会从这个备份读取，不会从本地的appsettings.json读取。这个备份会比你的appsettingjson新。
不能也把appsettingjson 也更新了吗?

**Comment by kklldog** [comment]
> > > 所有节点都挂了，是不是从appconfig里面读取配置，还是有专门的缓存文件,
> > > 直接修改appconfig这样不是更加好吗
> > 
> > 
> > 每次拉取配置成功会在本地存一个备份，如果所有节点都连不上会从这个备份读取，不会从本地的appsettings.json读取。这个备份会比你的appsettingjson新。
> 
> 不能也把appsettingjson 也更新了吗?
1.你这样是吧appsettingjson跟服务器上的配置1比1复制，但是有人不是这么想的啊，比如有人会把固定的一些配置，比如loglevel还是放appsettingjson上或者别的什么，每个人的需求都不一样
2.appsettingjson这个文件也不一定有啊，有的人可能会换个名字
