### ISSUE TITLE
appsettings.json中的Urls配置不生效

### ISSUE THREAD

**Issue by zqlovejyc** [kklldog/AgileConfig#25]
把appsettings.json中的配置导入到AgileConfig中，里面的Urls配置项不起作用，相同的配置在Apollo中是ok的，麻烦作者给看看到底是啥原因？

**Comment by kklldog** [comment]
你看看导入后生成的键值对不对？
要不把appsettings.json贴出来

**Comment by zqlovejyc** [comment]
> 你看看导入后生成的键值对不对？
> 要不把appsettings.json贴出来

可以确定是没有问题的，我是直接导入Json文件的，具体如下：
![image](https://user-images.githubusercontent.com/19462884/115648444-04eca800-a358-11eb-978d-70eef9195e32.png)

**Comment by kklldog** [comment]
> > 你看看导入后生成的键值对不对？
> > 要不把appsettings.json贴出来
> 
> 可以确定是没有问题的，我是直接导入Json文件的，具体如下：
> ![image](https://user-images.githubusercontent.com/19462884/115648444-04eca800-a358-11eb-978d-70eef9195e32.png)

那是根据Urls读取不到对应的值？

**Comment by zqlovejyc** [comment]
> > > 你看看导入后生成的键值对不对？
> > > 要不把appsettings.json贴出来
> > 
> > 
> > 可以确定是没有问题的，我是直接导入Json文件的，具体如下：
> > ![image](https://user-images.githubusercontent.com/19462884/115648444-04eca800-a358-11eb-978d-70eef9195e32.png)
> 
> 那是根据Urls读取不到对应的值？

是程序没有根据指定的端口号启动，而是采用默认的5000端口，但是同样的配置我在Apollo中和直接在appsettings.json中是没有问题的，不知道是什么原因导致的Urls配置的端口没有生效。

**Comment by kklldog** [comment]
知道你的意思，可能是跟远程的配置异步加载的原因，app 启动的时候配置可能还没加载完成。

**Comment by kklldog** [comment]
我知道了，因为asp.net core读取的时候使用了urls这个小写的key。其他configuralprovider读取配置的时候使用了忽略大小写的方案。而agileconfig.client大小写敏感。
你可以把key改成urls，应该就可以。
或者更新最新的client 1.1.8.2 我已经改成了大小写不敏感。

**Comment by zqlovejyc** [comment]
> 我知道了，因为asp.net core读取的时候使用了urls这个小写的key。其他configuration provider读取配置的时候使用了忽略大小写的方案。而agileconfig.client大小写敏感。
> 你可以把key改成urls，应该就可以。
> 或者更新最新的client 1.1.8.2 我已经改成了大小写不敏感。

刚升级过了，测试了下没有问题，谢谢！
