### ISSUE TITLE
客户端数量一直为0

### ISSUE THREAD

**Issue by zqlovejyc** [kklldog/AgileConfig#26]
客户端可以正常读取服务端配置数据，但是UI界面一直显示0，没有客户端数据，是哪里需要配置吗？

另外一个问题是：查看了本地缓存，只有其中一个应用的缓存，其他应用未发现缓存文件，不知道这个是否正常？

**Comment by kklldog** [comment]
可能你没把当前节点加入管理队列。
本地只缓存client连接的时候指定的appid的配置数据。

**Comment by zqlovejyc** [comment]
> 可能你没把当前节点加入管理队列。
> 本地只缓存client连接的时候指定的appid的配置数据。

这个怎么把客户端加入管理队列？
本地缓存我配置了3个应用：具体如下
`"AgileConfig": {
    "Appsettings": {
      "AppId": "Appsettings",
      "Secret": "Appsettings",
      "Nodes": "http://localhost:5000"
    },
    "Ocelot": {
      "AppId": "Ocelot",
      "Secret": "Ocelot",
      "Nodes": "http://localhost:5000"
    },
    "Consul": {
      "AppId": "Consul",
      "Secret": "Consul",
      "Nodes": "http://localhost:5000"
    }
  }`

**Comment by kklldog** [comment]
就是在控制台，节点，添加，把当前节点加进去啊。
啥？你启动了3个client？

**Comment by zqlovejyc** [comment]
> 就是在控制台，节点，添加，把当前节点加进去啊。
> 啥？你启动了3个client？

我说的是客户端的数量，不是节点的数量，我看客户端是没办法手动添加的；
是启动了3个client，我看是支持的，只不过本地缓存只有一个，还有能否添加类似Apollo的命名空间的功能，这样我就可以公用一个应用了。

**Comment by kklldog** [comment]
> > 就是在控制台，节点，添加，把当前节点加进去啊。
> > 啥？你启动了3个client？
> 
> 我说的是客户端的数量，不是节点的数量，我看客户端是没办法手动添加的；
> 是启动了3个client，我看是支持的，只不过本地缓存只有一个，还有能否添加类似Apollo的命名空间的功能，这样我就可以公用一个应用了。

我明白了，如果new 3 个 client的话确实本地只会留最后一个，因为文件名都一样，这个可以改进下。
你控制台修改配置，client能实时更新吗？感觉是没连接上去。你内网是不是有nginx？
你可以再建一个应用，关联其他3个应用就可以使用一个appid读取了。

**Comment by zqlovejyc** [comment]
> > > 就是在控制台，节点，添加，把当前节点加进去啊。
> > > 啥？你启动了3个client？
> > 
> > 
> > 我说的是客户端的数量，不是节点的数量，我看客户端是没办法手动添加的；
> > 是启动了3个client，我看是支持的，只不过本地缓存只有一个，还有能否添加类似Apollo的命名空间的功能，这样我就可以公用一个应用了。
> 
> 我明白了，如果new 3 个 client的话确实本地只会留最后一个，因为文件名都一样，这个可以改进下。
> 你控制台修改配置，client能实时更新吗？感觉是没连接上去。你内网是不是有nginx？
> 你可以再建一个应用，关联其他3个应用就可以使用一个appid读取了。

修改完控制台配置，client能够实时更新，但是还是不是客户端信息，内网没有使用nginx

**Comment by kklldog** [comment]
多个缓存的问题要不你改一下来个pr？
你确定是实时更新吗？还是过几秒之后更新？你可以帮忙看下server端的日志吗？控制台会每个5秒去节点拉节点的信息，有个trace的日志能否帮忙看看？

**Comment by zqlovejyc** [comment]
> 多个缓存的问题要不你改一下来个pr？
> 你确定是实时更新吗？还是过几秒之后更新？你可以帮忙看下server端的日志吗？控制台会每个5秒去节点拉节点的信息，有个trace的日志能否帮忙看看？

多个缓存的我看下源码
server端的日志如下：
[[Info]AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.log](https://github.com/kklldog/AgileConfig/files/6362474/Info.AgileConfig.Server.Apisite.Websocket.WebsocketHandlerMiddleware.log)

**Comment by kklldog** [comment]
[Trace]AgileConfig.Server.Service.RemoteServerNodeProxy.log 看这个

**Comment by zqlovejyc** [comment]
> [Trace]AgileConfig.Server.Service.RemoteServerNodeProxy.log 看这个

没有这个文件的日志，奇了怪了

**Comment by kklldog** [comment]
> > [Trace]AgileConfig.Server.Service.RemoteServerNodeProxy.log 看这个
> 
> 没有这个文件的日志，奇了怪了

把LogLevel 改成Trace

**Comment by zqlovejyc** [comment]
多客户端本地缓存PR已提交

**Comment by zqlovejyc** [comment]
> > > [Trace]AgileConfig.Server.Service.RemoteServerNodeProxy.log 看这个
> > 
> > 
> > 没有这个文件的日志，奇了怪了
> 
> 把LogLevel 改成Trace

重启下服务端后，客户端数量显示了，谢谢！

**Comment by kklldog** [comment]
感谢pr，nuget已经更新。

**Comment by zqlovejyc** [comment]
> 感谢pr，nuget已经更新。

又提交了个pr
![image](https://user-images.githubusercontent.com/19462884/115830633-27a7bb00-a443-11eb-9126-73fed56db77c.png)
