### ISSUE TITLE
Mysql数据库utf8mb4编码，出现中文编码问题 

### ISSUE THREAD

**Issue by aion1998** [kklldog/AgileConfig#33]
![image](https://user-images.githubusercontent.com/19725014/122706820-50093580-d28b-11eb-906a-a3094de38a39.png)

如图..

**Comment by kklldog** [comment]
是所有页面都乱码，还是就日志这里乱码

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/122715015-d711da00-d29a-11eb-9dce-7dbc7e5c3257.png)
![image](https://user-images.githubusercontent.com/19725014/122715031-df6a1500-d29a-11eb-865e-2a0fd3fc2970.png)

基本上只要最是中文存数据库的，都是

**Comment by kklldog** [comment]
mysql版本号多少

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/122715425-6c14d300-d29b-11eb-8bbe-ce01824faea0.png)

5.7.26

**Comment by kklldog** [comment]
晚上回去试试

**Comment by aion1998** [comment]
> 晚上回去试试

前辈，咋样了

**Comment by kklldog** [comment]
在连接串上加上 Character Set=utf8mb4
