### ISSUE TITLE
登录界面显示不了，是缺少文件么？

### ISSUE THREAD

**Issue by zhangning123798** [kklldog/AgileConfig#34]
appsettings.Development.json
  "adminConsole": true,
  "preview_mode": false,
  "db": {
    "provider": "sqlite", //sqlite,mysql,sqlserver,npgsql,oracle
    "conn": "Data Source=agile_config.db"

数据库表：
user表
1	admin	123456			2021-02-01	2021-02-01	0
super_admin	super_admin	123456			2021-02-01	2021-05-01	0

**Comment by kklldog** [comment]
源码直接运行？
请先编译react-ui-antd项目把dist内的产物复制到apisite项目的wwwroot/ui目录下。
