### ISSUE TITLE
关于支持多数据库的建议

### ISSUE THREAD

**Issue by teotws** [kklldog/AgileConfig#4]
叶老板开发的ORM FreeSql支持数据库非常多，如果需要支持多数据库可能用这个来实现比较方便。不知道该项目更换ORM的难度，只是提个建议。感谢作者开发这么好用的工具~

**Comment by kklldog** [comment]
> 叶老板开发的ORM FreeSql支持数据库非常多，如果需要支持多数据库可能用这个来实现比较方便。不知道该项目更换ORM的难度，只是提个建议。感谢作者开发这么好用的工具~

更换毫无难度，EFCore应该也支持不少吧。我只是没环境去测，比如Oracle什么的。。。有空再多支持几个

**Comment by teotws** [comment]
> > 叶老板开发的ORM FreeSql支持数据库非常多，如果需要支持多数据库可能用这个来实现比较方便。不知道该项目更换ORM的难度，只是提个建议。感谢作者开发这么好用的工具~
> 
> 更换毫无难度，EFCore应该也支持不少吧。我只是没环境去测，比如Oracle什么的。。。有空再多支持几个

FreeSql主要是支持了国产数据库，我们现有项目用到国产数据库所以用起来迁移数据库的成本比较低，而且对特定数据库的依赖包是分开的，可以按需安装，作者维护挺勤快的，测试多数据库交给他就行了～

**Comment by kklldog** [comment]
> > > 叶老板开发的ORM FreeSql支持数据库非常多，如果需要支持多数据库可能用这个来实现比较方便。不知道该项目更换ORM的难度，只是提个建议。感谢作者开发这么好用的工具~
> > 
> > 
> > 更换毫无难度，EFCore应该也支持不少吧。我只是没环境去测，比如Oracle什么的。。。有空再多支持几个
> 
> FreeSql主要是支持了国产数据库，我们现有项目用到国产数据库所以用起来迁移数据库的成本比较低，而且对特定数据库的依赖包是分开的，可以按需安装，作者维护挺勤快的，测试多数据库交给他就行了～

好的 我去考察下。

**Comment by kklldog** [comment]
我切到freesql了，你们是用啥国产数据库？我支持一下
