### ISSUE TITLE
关于配置项相关的疑问

### ISSUE THREAD

**Issue by Ran-snow** [kklldog/AgileConfig#5]
![image](https://user-images.githubusercontent.com/18158510/87620396-05b13780-c751-11ea-8656-b2dc976400b7.png)

目前是值支持键值对这种形式吗？ 比如我想在客户端里读出一个配置节点的对象，应该怎么操作呢？

**Comment by kklldog** [comment]
> 目前是值支持键值对这种形式吗？ 比如我想在客户端里读出一个配置节点的对象，应该怎么操作呢？
目前只支持简单的k/v，或者利用ioption支持一层的简单对象嵌套。
比如你图上配置的有2个方法来处理
1.完完全全当键值对来处理，根据dbconn获取值然后自己反序列化成对象，我觉得这样挺好，简单暴力，一目了然。
2.你可以这样配置: group=dbcon key=friut value=123 然后定义一个class xxx{ public string friut {get;set;} } 然后可以使用ioption模式自动反序列化， 参考sample示例的使用方式。

**Comment by kklldog** [comment]
> ![image](https://user-images.githubusercontent.com/18158510/87620396-05b13780-c751-11ea-8656-b2dc976400b7.png)
> 
> 目前是值支持键值对这种形式吗？ 比如我想在客户端里读出一个配置节点的对象，应该怎么操作呢？

目前只支持简单的k/v，或者利用ioption支持一层的简单对象嵌套。
比如你图上配置的有2个方法来处理
1.完完全全当键值对来处理，根据dbconn获取值然后自己反序列化成对象，我觉得这样挺好，简单暴力，一目了然。
2.你可以这样配置: group=dbcon key=friut value=123 然后定义一个class xxx{ public string friut {get;set;} } 然后可以使用ioption模式自动反序列化， 参考sample示例的使用方式。

**Comment by Ran-snow** [comment]
了解了，因为我这现有的配置，有个配置项的值是个列表...  我了解下源代码先，
