### ISSUE TITLE
你好，请问添加批量添加配置，有考虑支持嘛？

### ISSUE THREAD

**Issue by BootsShu** [kklldog/AgileConfig#6]

**Comment by kklldog** [comment]
可能会开发json文件导入功能。

**Comment by BootsShu** [comment]
> 可能会开发json文件导入功能。

点赞，追加导入json,是一个非常实用的功能。比阿波罗配种中心体验还要好点，我就正准备从阿波罗切换到AgileConfig，它还消耗内存资源了。

**Comment by BootsShu** [comment]
1

**Comment by kklldog** [comment]
> > 可能会开发json文件导入功能。
> 
> 点赞，追加导入json,是一个非常实用的功能。比阿波罗配置中心体验还要好点，我就正准备从阿波罗切换到AgileConfig，它太耗内存资源了。

已经支持了，可以把appsettings.json直接导入进去

**Comment by BootsShu** [comment]
> > > 可能会开发json文件导入功能。
> > 
> > 
> > 点赞，追加导入json,是一个非常实用的功能。比阿波罗配置中心体验还要好点，我就正准备从阿波罗切换到AgileConfig，它太耗内存资源了。
> 
> 已经支持了，可以把appsettings.json直接导入进去

奈斯，太感谢了。 作者威武。
