### ISSUE TITLE
配置值长度不能超过200位;配置值长度不能超过200位

### ISSUE THREAD

**Issue by xueandfeng** [kklldog/AgileConfig#8]
![image](https://user-images.githubusercontent.com/20178645/88528219-e65bb980-d030-11ea-85b6-0d7b1d18c291.png)
长度加大点吧。有些设置会超过这个限制

**Comment by kklldog** [comment]
哈哈，好的，有几个兄弟反馈了,可是多大合适啊，总不能varcharmax 吧

**Comment by xueandfeng** [comment]
我设置改的是2048，因为对接第三方平台需要的key密钥他们给的有这么大，我觉得可以考虑设置max毕竟这个是人为控制的，总不会有人弄出很大值吧

**Comment by kklldog** [comment]
> 我设置改的是2048，因为对接第三方平台需要的key密钥他们给的有这么大，我觉得可以考虑设置max毕竟这个是人为控制的，总不会有人弄出很大值吧

我权衡一下吧。

**Comment by kklldog** [comment]
现在长度拉到了nvarchar4000，查了一下如果长度超过sqlserver长度超过8000会有点性能开销。
