### ISSUE TITLE
请问下json字符串数组的形式需要怎么定义

### ISSUE THREAD

**Issue by qwedc2** [kklldog/AgileConfig#9]

**Comment by kklldog** [comment]
建议直接定义成字符串["a","b"] ，然后自己反序列化。

**Comment by wwwu** [comment]
> 建议直接定义成字符串["a","b"] ，然后自己反序列化。

可以通过给键值加:下标实现：
| Group | Key | Value | 
| :- | :- | :- | 
| - | KeyName:0  | a |
| - | KeyName:1 | b | 

```
class MyConfig
{
    public string[] KeyName { get; set; }
}
```

**Comment by kklldog** [comment]
> > 建议直接定义成字符串["a","b"] ，然后自己反序列化。
> 
> 可以通过给键值加:下标实现：
> 
> Group	Key	Value
> -	KeyName:0	a
> -	KeyName:1	b
> ```
> class MyConfig
> {
>     public string[] KeyName { get; set; }
> }
> ```
赞，翻译成k/v是这样，就是有点让人难理解
